name: Semgrep Static Scan

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container: semgrep/semgrep:latest

    steps:
      - uses: actions/checkout@v6

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config p/ci \
            --config p/security-audit \
            --config p/secrets \
            --verbose \
            --max-target-bytes 0 \
            --no-git-ignore \
            --sarif --output semgrep.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
